apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: aws-secrets
  namespace: default
spec:
  type: secretstores.aws.secretmanager
  version: v1
  metadata:
    - name: region
      value: us-east-1
    - name: accessKey
      value: test
    - name: secretKey
      value: test
    - name: endpoint
      value: http://localhost:4566